### ISSUE TITLE
How to use this template

### ISSUE THREAD

**Issue by IttiwatNir** [ddiyteam/webapitemplate_netcore#1]
I just started studying C# language and dotnet core 
I want to know how to use this template 
Thank you.

**Comment by ddiyteam** [comment]
This template will helps you when you need to develop web api service. It includes all configurations for fast start (logging, auth, apidocs, repositories and logic layers and etc). You need to download template from ms marketplace or clone it from git repo.
You may use sample services/repositories models and contracts (CarsService,  ICarsRepository and etc) or create your own for your needs. 

- CarsController - sample CRUD, needs mysql db (if you does not have it or don't want to use it - you may implement ICarsRepository interface for your needs or create your own interface and models)
- TodoController - proxy with http client (.NET Core builtin HttpClientFactory - you can find more info about this on ms docs [Use HttpClientFactory to implement resilient HTTP requests](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests) )
- TokenController - simple JWT token generation/validation for auth

Thank you.

**Comment by hausmaen** [comment]
Hi, I tried as well but I get hundreds of errors when creating a new project with it. expecially $ext_safeprojectname$ is referenced several times which seems to be some template parameter not replaced by value. Maybe I use it the wrong way around? Which template do I need to use first?

Thank you

**Comment by derob357** [comment]
I want to use SQL Server. But there is no documentation on how to add your own entity or how to connect to sql server. Can you provide a description of the template? For example what is the DbUp folders purpose. How to use another entity besides cars? Do I start with the DAL? This template is very extensive in features but there is no details on any of them and how they relate. When I clone this project and run it, the swagger page comes up, I execute the first api call and get unauthorized. Could you provide a walkthrough video or a tutorial or something? If not Thanks for the effort...
