### ISSUE TITLE
Warning in Startup.cs when calling services.BuildServiceProvider()

### ISSUE THREAD

**Issue by RedFeet** [ddiyteam/webapitemplate_netcore#2]
How can I solve the cause of this warning?

Warning	ASP0000	Calling 'BuildServiceProvider' from application code results in an additional copy of singleton services being created. Consider alternatives such as dependency injecting services as parameters to 'Configure'.

in D:\Code\ProjectName\\Startup.cs, line 78:
```
            services.AddSwaggerGen(opt =>
            {
                var provider = services.BuildServiceProvider().GetRequiredService<IApiVersionDescriptionProvider>();

```

**Comment by ddiyteam** [comment]
Thank you for your question.
You need to move swagger ApiVersioning parameters configuration to separate class inherited from IConfigureOptions (where IApiVersionDescriptionProvider interface was injected in constructor).
Then register this class in Startup. 
See commit https://github.com/ddiyteam/webapitemplate_netcore/commit/7b4eb71b97663ed7fb02bbdf91939c393b69370b
Or you may upgrade WebApiTemplateNetCore3 template to v1.2 from Visual Studio marketplace.
